apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-aws-ssm
  namespace: external-secrets
spec:
  provider:
    aws:
      service: ParameterStore
      # define a specific role to limit access
      # to certain secrets
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
