apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${environment}-frontend-argocd-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: ${environment}-${workspace}-frontend
    server: ''
  source:
      path: ${frontend_k8_path}
      repoURL: ${helm_repo_url}
      targetRevision: ${frontend_target_revision}
      helm:
        valueFiles:
          - values.${workspace}.yaml
        releaseName:
        parameters:
          - name: image_uri
            value: ${frontend_image_uri}
          - name: hosturl
            value: app.${workspace}.${hosturl}
  sources:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
